language:
    - cpp

compiler:
    - gcc
    ##- clang

env:
    - BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release"
    - BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Release"
    - BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Debug"
    - BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug"

before_install:
#    - sudo add-apt-repository ppa:apokluda/boost1.53 --yes
#    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes # libstdc++-4.8
#    - if [ "${CXX}" == "clang++" ]; then sudo add-apt-repository --yes ppa:h-rayflood/llvm; fi # clang++-3.2
    - sudo apt-get update

install:
    - sudo apt-get install libboost-system-dev
    - sudo apt-get install libboost-regex-dev
    - sudo apt-get install libboost-filesystem-dev
    - sudo apt-get install openssl

#before_script:
#    # update compilers
#    - if [ "${CXX}" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
#    - if [ "${CXX}" == "clang++" ]; then export CXX="clang++-3.2" CC="clang-3.2"; fi

script:
    - rm -rf _build || true
    - mkdir _build
    - cd _build
    - cmake -D CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
    - make 
    - ctest --output-on-failure .

notifications:
  email:
    recipients:
      - thiagoh@gmail.com
    on_success: change
    on_failure: always